#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: Origin Of The (High Frequency) Extra-cellular Signal
#+DATE: <2016-01-14 jeu.>
#+AUTHOR: Christophe Pouzat
#+EMAIL: christophe.pouzat@parisdescartes.fr
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.3)
#+PROPERTY: header-args:python *Python* :session  :results pp

#+NAME: emacs-set-up
#+BEGIN_SRC emacs-lisp :results silent :exports none
(setq py-shell-name "~/anaconda3/bin/ipython")

(defun update-tag ()
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((count 1))
      (while (re-search-forward "\\tag{\\([0-9]+\\)}" nil t)
        (replace-match (format "%d" count) nil nil nil 1)
        (setq count (1+ count)))))
  )
#+END_SRC


* Introduction

We want to explore here the basic properties of the /extra-cellular/ potential generated by a uniform active---that is, able to propagate an action potential (or /spike/)---cable or axon. We are going to use the conductance model of [[http://onlinelibrary.wiley.com/doi/10.1113/jphysiol.1952.sp004764/abstract][Hodgkin and Huxlek (1952)]] together with the cable model making the "full" H & H model.

Remember that H & H /did not/ solve their full model in their /opus magnum/, remember also that the /mechanical calculator/ they had at this time was far less powerful that any of the smartphones everyone has nowadays in his/her pocket. They used a "trick" looking at the propagation of a waveform without deformation at a constant speed $\theta$, that is, a spike or action potential. In this way the spatial derivatives of the membrane potential can be expressed as time derivatives (as we will see bellow) and the partial differential equation (PDE) of the full model can be replaced by ordinary differential equations (ODE).

So we are going to start by deriving the expression of the extra-cellular potential generated by a "cable like neurite"---a neurite with a large length to radius ratio---that can approximated by a /line source/. We will follow a classical development that is very clearly explained in the book of Plonsey and Barr (2007) /Bioelectricity. A Quantitative Approach/, published by Springer. This development will lead us to an equation relating the extra-cellular potential to the integral of the weighted second partial derivative of the membrane potential with respect to space, $\partial^2 V_m(x,t) / \partial x^2$. The H & H model will give us actual values for this derivative but that will require a numerical solution. We will then explore the effect of the axonal diameter on the extra-cellular potential. 
